gazebo_ros_control:
  pid_gains:
    sara_1_joint1: {p: 300.0, i: 0.1, d: 1.0, i_clamp: 0.2}
    sara_1_joint2: {p: 300.0, i: 0.1, d: 1.0, i_clamp: 0.2}
    sara_1_joint3: {p: 300.0, i: 0.1, d: 1.0, i_clamp: 0.2}
    sara_1_joint4: {p: 300.0, i: 0.1, d: 1.0, i_clamp: 0.2}
    sara_1_joint5: {p: 300.0, i: 0.1, d: 1.0, i_clamp: 0.2}
    sara_1_joint6: {p: 300.0, i: 0.1, d: 1.0, i_clamp: 0.2}
    sara_1_gripper_sub: {p: 300.0, i: 0.1, d: 1.0, i_clamp: 0.2}
    sara_2_joint1: {p: 300.0, i: 0.1, d: 1.0, i_clamp: 0.2}
    sara_2_joint2: {p: 300.0, i: 0.1, d: 1.0, i_clamp: 0.2}
    sara_2_joint3: {p: 300.0, i: 0.1, d: 1.0, i_clamp: 0.2}
    sara_2_joint4: {p: 300.0, i: 0.1, d: 1.0, i_clamp: 0.2}
    sara_2_joint5: {p: 300.0, i: 0.1, d: 1.0, i_clamp: 0.2}
    sara_2_joint6: {p: 300.0, i: 0.1, d: 1.0, i_clamp: 0.2}
    sara_2_gripper_sub: {p: 300.0, i: 0.1, d: 1.0, i_clamp: 0.2}



# Publish joint_states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
