controller_list:
  - name: sara1_arm_controller
    action_ns: follow_joint_trajectory
    type: position_controllers/JointTrajectoryController
    default: True 
    joints:
      - sara_1_joint1
      - sara_1_joint2
      - sara_1_joint3
      - sara_1_joint4
      - sara_1_joint5
      - sara_1_joint6

  - name: sara1_gripper_controller
    action_ns: gripper_action
    type: effort_controllers/JointTrajectoryController 
    joints:
      - sara_1_gripper

  - name: sara2_arm_controller
    action_ns: follow_joint_trajectory
    type: position_controllers/JointTrajectoryController
    default: False 
    joints:
      - sara_2_joint1
      - sara_2_joint2
      - sara_2_joint3
      - sara_2_joint4
      - sara_2_joint5
      - sara_2_joint6

  - name: sara2_gripper_controller
    action_ns: gripper_action
    type: effort_controllers/JointTrajectoryController
    joints:
      - sara_2_gripper
